Models/Department.cs
using System.ComponentModel.DataAnnotations;

namespace UMSTestJS.Models
{
    public class Department
    {
        [Key]
        public int Id { get; set; }

        [Required, StringLength(80)]
        public string Name { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace UMSTestJS.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Student.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UMSTestJS.Models
{
    public class Student
    {
        [Key]
        public int Id { get; set; }
        
        [Required, StringLength(80)]
        public string Name { get; set; }
        public Department Department { get; set; }
        public int DepartmentId { get; set; }
        
    }
}

Models/ViewModels/StudentViewModel.cs
using System.Collections.Generic;

namespace UMSTestJS.Models.ViewModels
{
    public class StudentViewModel
    {
        public Student Student { get; set; }
        public Department Department { get; set; }
        public IEnumerable<Student> Students { get; set; }
        public IEnumerable<Department> Departments { get; set; }
        
    }
}

Controllers/DepartmentController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UMSTestJS.Data;
using UMSTestJS.Models;
using UMSTestJS.Models.ViewModels;

namespace UMSTestJS.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly UMSTestJSDbContext context;

        [BindProperty]
        public StudentViewModel studentViewModel { get; set; }
        public DepartmentController(UMSTestJSDbContext context)
        {
            this.context = context;
            studentViewModel = new StudentViewModel()
            {
                Department = new Department(),
                Departments = context.Departments.ToList()
            };
        }
        public IActionResult Index() => View(studentViewModel);
        
        public async Task<IActionResult> AddDepartment(Department department)
        {
            if(ModelState.IsValid)
            {
                await context.Departments.AddAsync(department);
                await context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using UMSTestJS.Models;

namespace UMSTestJS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StudentController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UMSTestJS.Data;
using UMSTestJS.Models;
using UMSTestJS.Models.ViewModels;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using System.Data;

namespace UMSTestJS.Controllers
{
    public class StudentController : Controller
    {
        private readonly UMSTestJSDbContext context;
        public IConfiguration configuration { get; }

        [BindProperty]
        public StudentViewModel studentViewModel { get; set; }
        public StudentController(UMSTestJSDbContext context, IConfiguration configuration)
        {
            this.configuration = configuration;
            this.context = context;
            studentViewModel = new StudentViewModel()
            {
                Student = new Student(),
                Department = new Department(),
                Students = context.Students.ToList(),
                Departments = context.Departments.ToList(),
            };
        }
        public IActionResult Index()
        {
            return View(studentViewModel);
        }

        [HttpPost,ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterStudent(Student student)
        {
            if (ModelState.IsValid)
            {
                await context.Students.AddAsync(student);
                await context.SaveChangesAsync();
            }
            return RedirectToAction();
        }
        public async Task<IActionResult> DepartmentsListJsonReturn()
        {
            List<Department> departments = new List<Department>();
            departments = await (from department in context.Departments select department).ToListAsync();
            return Json(new SelectList(departments, "Id", "Name"));
            //return new JsonResult(departments);
            //return Json(context.Departments.Select(m => new { Id = m.Id, Name = m.Name})); 
        }

        [HttpPost,ValidateAntiForgeryToken]
        public async Task<IActionResult> AddDepartment(Department department)
        {
            if(ModelState.IsValid)
            {
                await context.Departments.AddAsync(department);
                await context.SaveChangesAsync();   
            }
            return RedirectToAction();
        }
    }
}

Views/Department/Index.cshtml
@model UMSTestJS.Models.ViewModels.StudentViewModel

@{
    ViewData["Title"] = "Index - Department"; 
}

<div class="col-12">
    <div class="row">
        <div class="col-4">
            <h2 class="text-primary">Departments List</h2>
        </div>
        <div align="right" class="col-8 ">
            <a data-toggle="modal" style="cursor: pointer;" data-target="#addDepartmentPageModal" class="btn btn-primary text-white form control"><i class="fas fa-plus"></i> Department</a>
        </div>
    </div>
    <br>

    @if(Model.Departments.Count() > 0)
    {
        <table id="tbl" class="table table-hover bordered table-sm text-center">
            <thead class="table table-primary">
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Departments)
                {
                    <tr>
                        <td>@Html.DisplayFor(m => item.Id)</td>
                        <td>@Html.DisplayFor(m => item.Name)</td>
                    </tr>
                } 
            </tbody>
        </table>
    }
    else
    {
        <p>No Departments</p>
    }
</div>

<div class="modal fade" id="addDepartmentPageModal" tabindex="-1" role="dialog" aria-labelledby="DepartmentLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="DepartmentLabel">Add New Department</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @* <partial name="_addDepartmentPartial" model="@Model.Department" />  *@
            <div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>

<script>
    $(document).ready(function () {
        $("#submit").click(function () {
            var url = '@Url.Action("AddDepartment","Department")';
            var Name = $("#name").val();
            var dataString = "Name="+Name ;
            if(Name != "") {
                $.ajax({
                    type:'GET',
                    url: url,
                    data: dataString,
                    success: function () {
                        $('#addDepartmentPageModal').modal('toggle');
                        document.getElementById("name").value = "";
                        $("#tbl").load(" #tbl");
                    },
                    error: function () {
                        alert("An unexpected error occured !");
                    }
                });
            }
            else {
                $("#ValidationMessage").append("You can't leave any fields empty").css('color', 'red');
                setTimeout(function () {
                    $("#ValidationMessage").html("");
                }, 3000);
            }
        });
    });
</script>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UMSTestJS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UMSTestJS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" data-toggle="dropdown" id="dd1" aria-haspopup="false" aria-expanded="true">Test Features Menu</a>
                            <div class="dropdown-menu" aria-labelledby="dd1">
                                <a asp-controller="Student" asp-action="Index" class="dropdown-item">Student</a>
                                <a asp-controller="Department" asp-action="Index" class="dropdown-item">Department</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - UMSTestJS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/49cbe8ebac.js" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_addDepartmentFormPartial.cshtml
@model Department

<div>
    <form id="addDepartmentsForm" method="POST" data-ajax="true" data-ajax-complete="DepartmentPageModalActions()"  asp-controller="Student" asp-action="AddDepartment">
        <div class="col-12">
            <div class="form-group">
                <div class="col-2 ">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-11">
                    <input type="text" class="form-control" id="name" asp-for="Name">
                </div>
            </div>
            <div class="form-group row col-12">
                <div class="col-6">
                    <button type="button" class="btn btn-secondary form-control" data-dismiss="modal">Close</button>
                </div>
                <div class="col-6">
                    <button type="submit" id="addDepartmentSubmit" class="btn btn-primary form-control"><i class="fas fa-plus"></i> &nbsp; Add</button>
                </div>
            </div>
        </div>
    </form>
</div>

<script>
    
    function DepartmentPageModalActions() {
        $('#addDepartmentPageModal').modal('toggle');
        document.getElementById("name").value = "";
        $("#addDepartmentsForm").load(" #addDepartmentsForm");
        $("#departmentsTable").load(" #departmentsTable");
    } 

</script>

Views/Shared/_addDepartmentModalPartial.cshtml
<div class="modal fade" id="addDepartmentPageModal" tabindex="-1" role="dialog" aria-labelledby="departmentLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="departmentLabel">Add New Department</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <partial name="_addDepartmentFormPartial" />
            </div>
        </div>
    </div>
</div>

Views/Shared/_createStudentPartial.cshtml
@model UMSTestJS.Models.ViewModels.StudentViewModel

<div class="modal fade" id="createStudentPageModal" tabindex="-1" role="dialog" aria-labelledby="StudentLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="StudentLabel">Register New Student</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <partial name="_registerStudentPartial" model="@Model" />
            </div>
        </div>
    </div>
</div>

Views/Shared/_departmentsIndexPartial.cshtml
@model IEnumerable<Department>

<div id="departmentsTable" class="col-6 col-sm-6">
    <h3 class="text-primary">Departments List</h3><br>
    @if(Model.Count() > 0)
    {
        <table class="table table-hover bordered table-sm text-center">
            <thead class="table table-primary">
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(m => item.Id)</td>
                        <td>@Html.DisplayFor(m => item.Name)</td>
                    </tr>
                } 
            </tbody>
        </table>
    }
    else
    {
        <p>No Departments</p>
    }
</div>

Views/Shared/_registerStudentFormPartial.cshtml
@model UMSTestJS.Models.ViewModels.StudentViewModel
@using UMSTestJS.Extentions

<div>
    <form method="POST" data-ajax="true" data-ajax-complete="StudentPageModalActions()"  asp-controller="Student" asp-action="RegisterStudent">
        <div class="col-12">
            <div class="form-group">
                <div class="col-2 ">
                    <label asp-for="Student.Name"></label>
                </div>
                <div class="col-11">
                    <input type="text" class="form-control" id="name"  asp-for="Student.Name">
                </div>
            </div>
            <div class="form-group">
                <div class="col-2 ">
                    <label asp-for="Department"></label>
                </div>
                <div class="col-11">
                    <select class="form-control" id="department" asp-for="Student.DepartmentId" asp-items="@Model.Departments.ToSelectListItems(Model.Student.DepartmentId)"></select>
                </div>
            </div>
            <div class="form-group row col-12">
                <div class="col-6">
                    <button type="button" class="btn btn-secondary form-control" data-dismiss="modal">Close</button>
                </div>
                <div class="col-6">
                    <button type="submit" class="btn btn-primary form-control"><i class="fas fa-plus"></i> &nbsp; Register</button>
                </div>
            </div>
        </div>
    </form>
</div>

<script>

    function StudentPageModalActions() {
        $('#registerStudentPageModal').modal('toggle');
        document.getElementById("name").value = "";
        document.getElementById("department").value = "";
        $("#studentsTable").load(" #studentsTable");
    }

</script>

Views/Shared/_registerStudentModalPartial.cshtml
<div class="modal fade" id="registerStudentPageModal" tabindex="-1" role="dialog" aria-labelledby="StudentLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="StudentLabel">Register New Student</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <partial name="_registerStudentFormPartial" />
            </div>
        </div>
    </div>
</div>

Views/Shared/_registerStudentPartial.cshtml
@model UMSTestJS.Models.ViewModels.StudentViewModel
@using UMSTestJS.Extentions

<div>
    <form method="POST" data-ajax="true" data-ajax-complete="PageModalActions()" asp-controller="Student" asp-action="RegisterStudent">
        <div class="col-12">
            <div class="form-group">
                <div class="col-2 ">
                    <label asp-for="Student.Name"></label>
                </div>
                <div class="col-11">
                    <input type="text" class="form-control" id="name"  asp-for="Student.Name">
                </div>
            </div>
            <div class="form-group">
                <div class="col-2 ">
                    <label asp-for="Department"></label>
                </div>
                <div class="col-11">
                    <select class="form-control" id="department" asp-for="Student.DepartmentId" asp-items="@Model.Departments.ToSelectListItems(Model.Student.DepartmentId)"></select>
                </div>
            </div>
            <div class="form-group row col-12">
                <div class="col-6">
                    <button type="button" class="btn btn-secondary form-control" data-dismiss="modal">Close</button>
                </div>
                <div class="col-6">
                    <button type="submit" class="btn btn-primary form-control"><i class="fas fa-plus"></i> &nbsp; Register</button>
                </div>
            </div>
        </div>
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script src="~/lib/jquery.unobtrusive-ajax/jquery.unobtrusive-ajax.min.js"></script>
<script>
    function PageModalActions() {
        $('#createStudentPageModal').modal('toggle');
        document.getElementById("name").value = "";
        document.getElementById("department").value = "";
        $("#tbl").load(" #tbl");
    }   
</script>

Views/Shared/_studentsIndexPartial.cshtml
@model IEnumerable<Student>

<div id="studentsTable" class="col-md-6 col-sm-3">
    <h3 class="text-primary">Students List</h3><br>
    @if(Model.Count() > 0)
    {
        <table class="table table-hover bordered table-sm text-center">
            <thead class="table table-primary">
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Department</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(m => item.Id)</td>
                        <td>@Html.DisplayFor(m => item.Name)</td>
                        <td>@Html.DisplayFor(m => item.Department.Name)</td>
                    </tr>
                } 
            </tbody>
        </table>
    }
    else
    {
        <p>No Students</p>
    }
</div>

Views/Student/Index.cshtml
@model UMSTestJS.Models.ViewModels.StudentViewModel

@{
    ViewData["Title"] = "Index";
    Layout="~/Views/Shared/_Layout.cshtml";  
}

<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script src="~/lib/jquery.unobtrusive-ajax/jquery.unobtrusive-ajax.min.js"></script>


<div class="col-md-12 col-sm-12 row">
    <div align="right" class="col-12">
        <a data-toggle="modal" style="cursor: pointer;" data-target="#addDepartmentPageModal" class="btn btn-primary text-white form control"><i class="fas fa-plus"></i> &nbsp; Department</a> &nbsp;
        <a data-toggle="modal" style="cursor: pointer;" id="registerStudent" data-target="#registerStudentPageModal" class="btn btn-primary text-white form control"><i class="fas fa-plus"></i> &nbsp; Student</a>
    </div>  
</div>
<br>
<div class="col-md-12 col-sm-12 row">
    <partial name="_studentsIndexPartial" model="@Model.Students" /> <br>
    <partial name="_departmentsIndexPartial" model="@Model.Departments" />
</div>

<partial name="_registerStudentModalPartial" />
<partial name="_addDepartmentModalPartial" model="@Model.Department" />

@section Scripts {
    <script> 
        $("#registerStudent").click(function () {
            $(document).ready(function () {
                
                var url = '@Url.Action("DepartmentsListJsonReturn","Student")';
                var departmentOptions = $("#department");

                $.getJSON(url, { id: departmentOptions.val() }, function (data) {

                    var options = '';
                    departmentOptions.html('');

                    $.each(data, function (i, department) {
                        options += "<option value='" + department.value + "'>" + department.text + "</option>";
                    });
                    departmentOptions.html(options);
                });
            });
        });
    </script>
}